Fixed distribution to work with plugin infrastructure.
* Added a lib folder containing the implementations
* Added automatic creation and population of lib folder to distribution
    module
* Changed init script to add lib folder to classpath

diff --git a/opennms-pris-dist/src/examples/opennms-pris b/opennms-pris-dist/src/examples/opennms-pris
--- a/opennms-pris-dist/src/examples/opennms-pris
+++ b/opennms-pris-dist/src/examples/opennms-pris
@@ -52,6 +52,12 @@ if [ ! -d "${PROG_DIR}" ]; then
    exit 3
 fi
 
+if [ ! -d "${PROG_DIR}/lib" ]; then
+   echo "Could not find library directory for ${NAME}-daemon"
+   echo "Please check if you have installed the program correctly to ${NAME}"
+   exit 3
+fi
+
 # Start: check if the daemon is already running
 #
 # if (running(PID_FILE)) {
@@ -69,7 +75,7 @@ start() {
       exit 4
    else
       cd ${PROG_DIR}
-      ${JAVA_BIN} -jar ${PROG_DIR}/${PROG} &>${LOG_FILE} &
+      ${JAVA_BIN} -classpath ${PROG_DIR}/lib -jar ${PROG_DIR}/${PROG} &>${LOG_FILE} &
       if [ ! $? -eq 0 ]; then
         echo "FAILED"
         exit 5
